services:
    vinabb.happyanniversaryemail.listener:
        class: vinabb\happyanniversaryemail\event\listener
        arguments:
            - '@dbal.conn'
            - '@cache.driver'
            - '@config'
            - '@user'
            - '@language'
            - '@template'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
