services:
    vinabb.happyanniversary.listener:
        class: vinabb\happyanniversary\event\listener
        arguments:
            - '@cache.driver'
            - '@config'
            - '@dbal.conn'
            - '@notification_manager'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }
    vinabb.happyanniversary.notification.type.happy_anniversary:
        class: vinabb\happyanniversary\notification\type\happy_anniversary
        scope: prototype
        arguments:
            - '@user_loader'
            - '@dbal.conn'
            - '@cache.driver'
            - '@user'
            - '@auth'
            - '@config'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.notification_types%'
            - '%tables.notifications%'
            - '%tables.user_notifications%'
        tags:
            - { name: notification.type }
